### ISSUE TITLE
제안서 리뷰

### ISSUE THREAD

**Issue by MisooKim2** [saine0501/C202309-P#1]
1. 기능 1: 멘티에게 보낼 메시지 출력의 경우, 인터넷 연결을 통해 실시간 입출력을 가정해야할 것 같습니다. 본 수업에서는 실시간 입출력은 배우지 않을 예정이기때문에 우려되지만, 학생 역량으로 구현하실 수 있거나, 특정 상황을 가정한다면 관계 없을 것 같습니다.
2. 각 기능별 입/출력이 보다 구체화될 필요가 있어보이니, 향후 구체적으로 작성하시길 바랍니다.
- 변경 사항은 제안서는 수정하지 마시고, 1차 진척보고서에 반영하여 주시길 바랍니다

**Comment by saine0501** [comment]
반영하여 진척보고서 작성하겠습니다.
